-- 019_deep_analysis_extended.sql
-- Migration 019: No-op stub. Consolidated into 015_reference_deep_analysis.sql.
-- extracted_glossary and extracted_foreshadowings columns are now defined in
-- the CREATE TABLE and via ADD COLUMN IF NOT EXISTS guards in 015_reference_deep_analysis.sql.
